name: ProximityTextChat
version: '1.0-SNAPSHOT'
main: com.rift.proximityTextChat.ProximityTextChat
api-version: '1.20'
commands:
  reloadPTC:
    description: Reloads PTC plugin config file
    usage: /reloadPTC
    permission: ptc.use
    permission-message: §cYou do not have permission to use this command.
  msg:
    description: Sends a private msg to a player
    usage: /msg <player> <message>
    aliases: [message, w, whisper, tell, t]
    permission: ptc.msg
    permission-message: §cYou do not have permission to use this command.
  reply:
    description: Replies with a private msg to a player
    usage: /reply <message>
    aliases: [reply, r]
    permission: ptc.msg
    permission-message: §cYou do not have permission to use this command.
permissions:
  ptc.use:
    description: If a user can use the PTC commands.
    default: op
  ptc.msg:
    description: If a user can send private messages.
    default: true